export const ACTION_TYPES = {
  FETCH_START_ALL_TASKS: " FETCH_START_ALL_TASKS",
  FETCH_START_ADD_TASK: "FETCH_START_ADD_TASK",
  FETCH_START_REMOVE_TASK: "FETCH_START_REMOVE_TASK",
  FETCH_START_TASK_TOGGLE: "FETCH_START_TASK_TOGGLE",
  FETCH_START_CREATE_TASK_VALUE: "FETCH_START_CREATE_TASK_VALUE",
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
  AUTH_START: "AUTH_START",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_ERROR: "AUTH_ERROR",
  AUTH_CLEAR_ERROR: "AUTH_CLEAR_ERROR",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  GET_TASKS: " GET_TASKS",
  ADD_TASK: "ADD_TASK",
  REMOVE_TASK: "REMOVE_TASK",
  TODO_TOGGLE_COMPLETED: "TODO_TOGGLE_COMPLETED",
  TODOS_UPDATE_COMPLETED_FILTER: "TODOS_UPDATE_COMPLETED_FILTER",
  REMOVE_COMPLETED_TASKS: "REMOVE_COMPLETED_TASKS",
  CREATE_TASK_VALUE: "CREATE_TASK_VALUE",
  NEWEST: "NEWEST",
  OLDEST: "OLDEST",
  NAME_ASC: "NAME_ASC",
  NAME_DESC: "NAME_DESC",
};

export const FILTER_OPTIONS = [
  { id: 0, title: "All", filterType: "todosAll" },
  { id: 1, title: "Completed", filterType: "completedTodos" },
];

export const FILTER_TYPES = {
  ALL: "todosAll",
  COMPLETED: "completedTodos",
};

export const KEY_CODES = {
  ENTER: "Enter",
  ESCAPE: "Escape",
};

export const SORTABLE_OPTIONS = [
  { value: "NEWEST", label: "Сначала новые" },
  { value: "OLDEST", label: "Сначала старые" },
  { value: "NAME_ASC", label: "По имени (А-Я)" },
  { value: "NAME_DESC", label: "По имени (Я-А)" },
];
